name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
      - name: STEP I - Checkout Sourcecode From Github Into Github Runner(Ubuntu-Latest)
        uses: actions/checkout@v3

      - name: STEP II - Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: STEP III - Build with Maven
        run: mvn -B package --file pom.xml

      - name: STEP IV - Create Directory And Move JAR Into It
        run: mkdir artifact && cp target/*.jar artifact

      - name: STEP V - Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifact
          path: artifact
          if-no-files-found: error
          retention-days: 90
